### ISSUE TITLE
Content security policy isn't allowing page to load.

### ISSUE THREAD

**Issue by martan-network** [passwordcockpit/frontend#34]
I've searched many ways to work around this but the CSP persists and does not allow the webpage to load. Please help

**Comment by bu3tt1** [comment]
Which version do you use?
Please share the docker-compose.yaml

**Comment by martan-network** [comment]
version: "3.5"
services:
    passwordcockpit:
        image: passwordcockpit/passwordcockpit:1.3.4
        container_name: passwordcockpit
        ports:
            # Use with PASSWORDCOCKPIT_SSL: disable
            # - "8080:8080" 
            # Use with PASSWORDCOCKPIT_SSL: enable
            - "4343:4343"
        volumes:
            - ./volumes/upload:/var/www/html/upload
            # Overwrite self-signed SSL certificate file
            # - ./volumes/ssl_certificate/passwordcockpit.crt:/etc/ssl/certs/passwordcockpit.crt:ro
            # - ./volumes/ssl_certificate/passwordcockpit.key:/etc/ssl/certs/passwordcockpit.key:ro
            # User and group same as host when use APACHE_RUN_USER and APACHE_RUN_GROUP
            #- /etc/group:/etc/group:ro
            #- /etc/passwd:/etc/passwd:ro
            #- /etc/shadow:/etc/shadow:ro
        environment:
            DB_UPSTREAM: http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:3000
            PASSWORDCOCKPIT_DATABASE_USERNAME: passwordcockpit_db_usr
            PASSWORDCOCKPIT_DATABASE_PASSWORD: 
            PASSWORDCOCKPIT_DATABASE_HOSTNAME: mysql
            PASSWORDCOCKPIT_DATABASE_DATABASE: passwordcockpit
            PASSWORDCOCKPIT_BLOCK_CIPHER_KEY: 
            PASSWORDCOCKPIT_AUTHENTICATION_SECRET_KEY: 
            # Use with PASSWORDCOCKPIT_SSL: disable
            # PASSWORDCOCKPIT_BASEHOST: http://localhost:8080
            # Use with PASSWORDCOCKPIT_SSL: enable
            PASSWORDCOCKPIT_BASEHOST: https://localhost:4343
            PASSWORDCOCKPIT_AUTHENTICATION_TYPE: password
            PASSWORDCOCKPIT_SWAGGER: disable
            PASSWORDCOCKPIT_SSL: enable
            PASSWORDCOCKPIT_ADMIN_PASSWORD: 
            #APACHE_RUN_USER: 1000
            #APACHE_RUN_GROUP: 1000
            #PASSWORDCOCKPIT_LDAP_USER_ATTR_UNIQUE_IDENTIFIER: ''
            #PASSWORDCOCKPIT_LDAP_USER_ATTR_NAME: ''
            #PASSWORDCOCKPIT_LDAP_USER_ATTR_SURNAME: ''
            #PASSWORDCOCKPIT_LDAP_USER_ATTR_MAIL: ''
            #PASSWORDCOCKPIT_LDAP_USER_ATTR_PHONE: ''
            #PASSWORDCOCKPIT_LDAP_HOST: '
            #PASSWORDCOCKPIT_LDAP_PORT: 389
            #PASSWORDCOCKPIT_LDAP_USERNAME: ''
            #PASSWORDCOCKPIT_LDAP_PASSWORD: ''
            #PASSWORDCOCKPIT_LDAP_BASEDN: ''
            #PASSWORDCOCKPIT_LDAP_ACCOUNTFILTERFORMAT: ''
            #PASSWORDCOCKPIT_LDAP_BINDREQUIRESDN: 'true'
            PASSWORDCOCKPIT_UPLOAD_ACCEPTED_MIMETYPES: 'pdf,zip'
            #PASSWORDCOCKPIT_DEBUG: true
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        container_name: mysql
        ports:
            - '3306:3306'
        volumes:
            - ./volumes/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_USER=
            - MYSQL_PASSWORD=
            - MYSQL_DATABASE=
        command: --character-set-server=utf8 --collation-server=utf8_unicode_ci

**Comment by bu3tt1** [comment]
Please use the last version: 1.4.0

Change in your docker-compose.yaml
`image: passwordcockpit/passwordcockpit:1.4.0`

**Comment by martan-network** [comment]
Thanks!
